name: Build and package regression model

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    
    - name: set auto-install of extensions
      run: az config set extension.use_dynamic_install=yes_without_prompt
      
    - name: install azure ml
      run: az extension add -n ml
    
    - name: retrieve the model
      run: az ml model download -n "boston-housing-regression" -v "1" -g "practical_mlops" -w "pratical_mlops" -p "."
    
    # - name: list current dir
    #   run: ls ./boston-housing-regression
    
    # - name: Authenticate to Docker hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_REGISTRY }}
        
    - name: build flask-app container
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/BrunoRammon/boston-housing:latest
        
